/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Franklin Castillo
 * Created: Apr 11, 2018
 */

-- CREATE TABLE CLIENT(
--     ID_CLIENT INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
--     DOCUMENT VARCHAR(20),
--     NAME VARCHAR(50),
--     ADDRESS VARCHAR(100),
--     ZONE VARCHAR(50),
--     PHONE VARCHAR(20),
--     EMAIL VARCHAR(50),
--     NOTE VARCHAR(20),
--     CREATED_DATE TIMESTAMP DEFAULT 'NOW',
--     STATUS BOOLEAN
-- )

CREATE TABLE PRODUCT(
    ID_PRODUCT      INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ID_SUPPLIER     INTEGER,
    PRODUCT_CODE    VARCHAR(20),
    DESCRIPCION     VARCHAR(200),
    CATEGORY        VARCHAR(50),
    PRICE1          DECIMAL(10,2),
    PRICE2          DECIMAL(10,2),
    PRICE3          DECIMAL(10,2),
    COST            DECIMAL(10,2),
    MIN_STOCK       INTEGER,
    MAX_STOCK       INTEGER,
    CREATED_DATE    TIMESTAMP DEFAULT 'NOW',
    STATUS          BOOLEAN
)

CREATE TABLE SUPPLIER(
    ID_SUPPLIER     INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    DOCUMENT        VARCHAR(20),
    NAME            VARCHAR(50),
    ADDRESS         VARCHAR(100),
    ZONE            VARCHAR(50),
    PHONE           VARCHAR(20),
    EMAIL           VARCHAR(50),
    NOTE            VARCHAR(20),
    CREATED_DATE    TIMESTAMP DEFAULT 'NOW',
    STATUS          BOOLEAN
)

CREATE TABLE USERS(
    ID_USER         INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    DOCUMENT        VARCHAR(20),
    USER_NAME       VARCHAR(50),
    PASSWORD        VARCHAR(50),
    NAME            VARCHAR(50),
    ADDRESS         VARCHAR(100),
    ZONE            VARCHAR(50),
    PHONE           VARCHAR(20),
    EMAIL           VARCHAR(50),
    NOTE            VARCHAR(20),
    CREATED_DATE    TIMESTAMP DEFAULT 'NOW',
    STATUS          BOOLEAN
)


