/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app.inventory.view.product;

import com.app.inventory.dao.controller.ClientJpaController;
import com.app.inventory.dao.controller.InventoryJpaController;
import com.app.inventory.dao.controller.InventoryTransJpaController;
import com.app.inventory.dao.controller.MainAppController;
import com.app.inventory.dao.controller.ProductJpaController;
import com.app.inventory.domain.Client;
import com.app.inventory.domain.Inventory;
import com.app.inventory.domain.InventoryTrans;
import com.app.inventory.domain.Product;
import com.app.inventory.printer.PrintReports;
import com.app.inventory.util.EntityManagerUtil;
import com.app.inventory.util.UtilInv;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Franklin Castillo
 */
public class ProductSalesForm extends javax.swing.JFrame {
        
    List<Inventory> listInv = null;
    List<Inventory> listInvFromDB = null;
    List<Product> listProduct= null;
    Client client = null;
    Product product = null;
    Inventory inventory = null;
    InventoryTrans invTrans = null; 
    InventoryJpaController inventoryController = null;
    ClientJpaController clientController = null;
    ProductJpaController productController = null;
    InventoryTransJpaController invTransController = null;
    private int lastNoTrans;  
    private int idProductRowClicked;
    private int idClientRowClicked;
    MainAppController mainController = new MainAppController();
    private int idClientClicked;
    
    private void initObjects(){
        inventoryController = new InventoryJpaController(EntityManagerUtil.getEntityManager().getEntityManagerFactory());
        clientController = new ClientJpaController(EntityManagerUtil.getEntityManager().getEntityManagerFactory());
        productController = new ProductJpaController(EntityManagerUtil.getEntityManager().getEntityManagerFactory());
        invTransController = new InventoryTransJpaController(EntityManagerUtil.getEntityManager().getEntityManagerFactory());
        ftxtQuantity.setFormatterFactory(UtilInv.getIntegerFormatFactory());
        datePicker.setDateToToday();
        datePicker.setName("datePicker");
        listInv = new ArrayList<Inventory>();
        listProduct = new ArrayList<Product>();
        listInvFromDB = inventoryController.findInventoryEntities();
        //lastNoTrans = inventoryController.getInventoryCount()+1; 
        txtLastTrans.setText(lastTrans());
        
        //Habilitar cuando se vaya a implementar esta funcionalidad
        lbPrice.setVisible(false);
        jcPriceToChoose.setVisible(false);
//        fillCombo("product");
//        fillCombo("client");
    }
    //private DecimalFormat dFormat = new DecimalFormat( "#,###,###,##0" );
    
    
    /**
     * Creates new form ProductEntryFor;m
     */
    public ProductSalesForm() {
        initComponents();
        //initObjects();
        loadTable(mainController.getSalesProductTableModel());
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogProduct = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDialogProduct = new javax.swing.JTable();
        btnOkProduct = new javax.swing.JButton();
        jDialogClient = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDialogClient = new javax.swing.JTable();
        btnOkClient = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtLastTrans = new javax.swing.JTextField();
        datePicker = new com.github.lgooddatepicker.components.DatePicker();
        jLabel9 = new javax.swing.JLabel();
        txtInStock = new javax.swing.JTextField();
        btnFindClient = new javax.swing.JButton();
        txtClientName = new javax.swing.JTextField();
        txtNote = new javax.swing.JTextField();
        txtClient = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtProduct = new javax.swing.JTextField();
        btnFindProduct = new javax.swing.JButton();
        txtProductDesc = new javax.swing.JTextField();
        ftxtQuantity = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        ftxtPrice = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtTotals = new javax.swing.JTextField();
        lbPrice = new javax.swing.JLabel();
        jcPriceToChoose = new javax.swing.JComboBox<>();

        jDialogProduct.setTitle("Listado de Productos");

        jTableDialogProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDialogProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDialogProductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableDialogProduct);

        btnOkProduct.setText("Ok");
        btnOkProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogProductLayout = new javax.swing.GroupLayout(jDialogProduct.getContentPane());
        jDialogProduct.getContentPane().setLayout(jDialogProductLayout);
        jDialogProductLayout.setHorizontalGroup(
            jDialogProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogProductLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogProductLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOkProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDialogProductLayout.setVerticalGroup(
            jDialogProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOkProduct)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialogClient.setTitle("Listado de Productos");

        jTableDialogClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDialogClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDialogClientMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableDialogClient);

        btnOkClient.setText("Ok");
        btnOkClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogClientLayout = new javax.swing.GroupLayout(jDialogClient.getContentPane());
        jDialogClient.getContentPane().setLayout(jDialogClientLayout);
        jDialogClientLayout.setHorizontalGroup(
            jDialogClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogClientLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOkClient, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDialogClientLayout.setVerticalGroup(
            jDialogClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOkClient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de la salida"));

        jLabel1.setText("Numero:");

        jLabel2.setText("Fecha:");

        jLabel4.setText("Nota:");

        jLabel5.setText("Cliente:");

        btnAdd.setText("Agregar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        btnAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAddKeyPressed(evt);
            }
        });

        jLabel8.setText("Cantidad:");

        txtLastTrans.setEditable(false);
        txtLastTrans.setName("txtLastTrans"); // NOI18N

        datePicker.setName("datePicker"); // NOI18N

        jLabel9.setText("Disponible:");

        txtInStock.setEnabled(false);

        btnFindClient.setText("Find");
        btnFindClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindClientActionPerformed(evt);
            }
        });

        txtClientName.setEditable(false);
        txtClientName.setEnabled(false);

        txtNote.setText("Una nota");
        txtNote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoteKeyPressed(evt);
            }
        });

        txtClient.setNextFocusableComponent(txtProduct);
        txtClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClientKeyPressed(evt);
            }
        });

        jLabel7.setText("Producto:");

        txtProduct.setNextFocusableComponent(ftxtQuantity);
        txtProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProductKeyPressed(evt);
            }
        });

        btnFindProduct.setText("Find");
        btnFindProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindProductActionPerformed(evt);
            }
        });

        txtProductDesc.setEditable(false);
        txtProductDesc.setEnabled(false);

        ftxtQuantity.setText("25");
        ftxtQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftxtQuantityFocusGained(evt);
            }
        });
        ftxtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftxtQuantityKeyPressed(evt);
            }
        });

        jLabel3.setText("Precio:");

        ftxtPrice.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ftxtPrice.setEnabled(false);
        ftxtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftxtPriceKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtLastTrans, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addComponent(txtClient, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnFindProduct)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProductDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnFindClient))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtClientName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtInStock, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ftxtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxtQuantity)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLastTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(datePicker, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(txtClient, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindClient)
                    .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(txtProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindProduct)
                    .addComponent(txtProductDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(txtInStock, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ftxtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(ftxtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnAdd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setText("Totales:");

        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClear.setText("Limpiar");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtTotals.setText("0");
        txtTotals.setEnabled(false);

        lbPrice.setText("Precio:");

        jcPriceToChoose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Precio 1", "Precio 2", "Precio 3" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotals, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jcPriceToChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbPrice)
                                        .addGap(105, 105, 105)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancel)
                                .addGap(18, 18, 18)
                                .addComponent(btnClear)
                                .addGap(19, 19, 19)
                                .addComponent(btnSave))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTotals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClear)
                    .addComponent(btnCancel)
                    .addComponent(btnDelete)
                    .addComponent(btnSave)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jcPriceToChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbPrice)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(mainController.getListInv() == null ){
            JOptionPane.showMessageDialog(this, "Debe agregar registros a la lista para poder continuar...", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{ 
            //Actualiza el inventario, descontando las ventas 
            mainController.getListInv().forEach(inv -> {
                int qtyOfItemOnList = inv.getStock();
                int newQtyOnInv = inventoryController.findInventory(inv.getIdInventory()).getStock()- inv.getStock();
                try {
                    //Inventory
                    inv.setStock(newQtyOnInv);
                    inventoryController.edit(inv);
                } catch (Exception ex) {
                    Logger.getLogger(ProductSalesForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                /*Inventory Transaction*/
                invTrans = new InventoryTrans();
                invTrans.setIdInventory(inv.getIdInventory());//sopesar el colocar el id del inventory creado en la linea de arriba
                invTrans.setIdProduct(inv.getIdProduct());
                invTrans.setIdSupplier(inv.getIdSupplier());
                invTrans.setIdClient(Integer.parseInt(txtClient.getText()));
                invTrans.setIdUser(1);//modificar cuando se haga modulo de user
                invTrans.setTransType("venta");
                invTrans.setDiscount(BigDecimal.ZERO);
                invTrans.setQuantity(qtyOfItemOnList);
                
                BigDecimal price = inventoryController.findInventory(inv.getIdInventory()).getPrice1();
                invTrans.setPricexunit(price);
                invTrans.setTotal(price.multiply(new BigDecimal(qtyOfItemOnList)));
                invTrans.setCreatedDate(inv.getLastUpdated());
            
                invTransController.create(invTrans);
                
                invTrans.setIdInventory(invTransController.findInventoryTransEntities().get(invTransController.findInventoryTransEntities().size()-1).getIdInventory());
                mainController.getListInvTrans().add(invTrans);
            });
            
            //Final
            JOptionPane.showMessageDialog(this, "Guardado satisfactoriamente");
            
            /********************imprimir reporte*****************************/
            PrintReports printReport = new PrintReports();
            String[] values = {txtLastTrans.getText(), datePicker.getDateStringOrEmptyString(), MainAppController.clientController.findClient(idClientClicked).getName()};
            printReport.productSalesReport(mainController.getListInv(), mainController.getListInvTrans() ,values);
                    
            mainController.getListInv().clear(); //this lista has to be empty to store new products that will be shown on the table
            mainController.getListInvTrans().clear();
            
            /*Limpiar elementos de la pantalla*/
            //UtilInv.clearTextFields(this.getContentPane());
            txtProduct.setText("");
            txtProductDesc.setText("");
            txtClient.setText("");
            txtClientName.setText("");
            txtInStock.setText("");
            ftxtPrice.setValue(0);
            ftxtQuantity.setValue(null);
            txtNote.setText("");
            txtTotals.setText("0");
            
            /**/
            //lastNoTrans = inventoryController.getInventoryCount()+1;
            //txtLastTrans.setText(String.valueOf(lastNoTrans));
            loadTable(mainController.getSalesProductTableModel());
            
            //Actualizando lista proveniente de BD
            listInvFromDB = inventoryController.findInventoryEntities();
//            int dialogButton = JOptionPane.YES_NO_OPTION;
//            int dialogResult = JOptionPane.showConfirmDialog(this, "Desea imprimir el recibo?", "Info", dialogButton);
//            if(dialogResult == 0) {
//                
//            } else {
//              System.out.println("No Option");
//            }
            txtLastTrans.setText(lastTrans());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        /*Al llegar a este punto, hay tres objetos inicializados: 
            -Product
            -Client
            -Inventory
        */
        
        if (txtProduct.getText().isEmpty() || txtClient.getText().isEmpty() || ftxtQuantity.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Favor completar campos requerido", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            int inStock = Integer.parseInt(txtInStock.getText());
            int prodQty = Integer.parseInt(ftxtQuantity.getText().replace(",", ""));
            if (prodQty < inStock) {

                if (mainController.getListInv().indexOf(inventory) == -1) { //no existe en la lista
                    inventory.setStock(prodQty);
                    inventory.setIdProduct(product.getIdProduct());
    ////                inventory.setIdSupplier(client.getIdClient());
                    inventory.setLastUpdated(UtilInv.getDateNow());
                    mainController.getListInv().add(inventory);
                }else{
                    Inventory inv = mainController.getListInv().get(mainController.getListInv().indexOf(inventory));
                    inv.setStock(inv.getStock() + prodQty);
//                    inventory.setStock(prodQty);
                    inv.setIdProduct(product.getIdProduct());
    //                inventory.setIdSupplier(client.getIdClient());
                    inv.setLastUpdated(UtilInv.getDateNow());
                    //mainController.getListInv().add(inv);
                }
//                listInvFromDB.forEach(inve -> {
//                    if(i.getIdProduct().equals(product.getIdProduct())){
                        //se crear un objeto con el inventario de ese producto
                        //Entrada inicial al inventario
//                        Inventory inventory = new Inventory();
//                        inventory.setIdSupplier(inv.getIdSupplier());
//                        inventory.setCost(ftxtCost.getText().trim().equals("") ? BigDecimal.ZERO : BigDecimal.valueOf(Double.parseDouble(ftxtCost.getText().trim().replace(",", ""))));
//                        inventory.setAvgCost(ftxtCost.getText().trim().equals("") ? BigDecimal.ZERO : BigDecimal.valueOf(Double.parseDouble(ftxtCost.getText().trim().replace(",", ""))));
//                        inventory.setMinStock(Integer.parseInt(jpMinStock.getValue().toString()));
//                        inventory.setStock(Integer.parseInt(jpInitialStock.getValue().toString()));
//                        inventory.setPrice1(ftxtPrice1.getText().trim().equals("") ? BigDecimal.ZERO :(BigDecimal) (ftxtPrice1.getText().trim().replace(",", "").isEmpty() ? 0 : BigDecimal.valueOf(Double.parseDouble(ftxtPrice1.getText().trim())))); 
//                        inventory.setPrice2(ftxtPrice2.getText().trim().equals("") ? BigDecimal.ZERO : (BigDecimal) (ftxtPrice2.getText().trim().replace(",", "").isEmpty() ? 0 : BigDecimal.valueOf(Double.parseDouble(ftxtPrice2.getText().trim())))); 
//                        inventory.setPrice3(ftxtPrice3.getText().trim().equals("") ? BigDecimal.ZERO : (BigDecimal) (ftxtPrice3.getText().trim().replace(",", "").isEmpty() ? 0 : BigDecimal.valueOf(Double.parseDouble(ftxtPrice3.getText().trim())))); 
//                        inventory.setPrice4(BigDecimal.ZERO);
//                        inventory.setIdProduct(product.getIdProduct());
//                        inventory.setTax(inventory.getCost().multiply(BigDecimal.valueOf(0.18)).intValue());//Pending
//                        inventory.setLastUpdated(new java.sql.Timestamp(date.getTime()));
////                        inventory.setStock(i.getStock());
//                        System.out.println(i.getStock());
//                        System.out.println(inventory);
//                        if (mainController.getListInv().indexOf(inve) == -1) { //no existe en la lista
//                            inve.setStock(prodQty);
//                            inve.setIdProduct(product.getIdProduct());
//            ////                inventory.setIdSupplier(client.getIdClient());
//                            inve.setLastUpdated(UtilInv.getDateNow());
//                            mainController.getListInv().add(inve);
//                        }else{
//                            Inventory inv = mainController.getListInv().get(mainController.getListInv().indexOf(inve));
//                            inv.setStock(inv.getStock() + prodQty);
//        //                    inventory.setStock(prodQty);
//                            inv.setIdProduct(product.getIdProduct());
//            //                inventory.setIdSupplier(client.getIdClient());
//                            inv.setLastUpdated(UtilInv.getDateNow());
//                            mainController.getListInv().add(inv);
//                        }
//                    }
//                });
//                inventory.setStock(prodQty);
//                inventory.setIdProduct(product.getIdProduct());
//////                inventory.setIdSupplier(client.getIdClient());
//                inventory.setLastUpdated(UtilInv.getDateNow());
    //            inv.setQuantity(prodQty);
    //            inv.setLastUpdated(date);
                
                
//                listInv.add(inventory);
//                product = productController.findProduct(inv.getIdProduct());
//                client = clientController.findClient(inv.getIdProveedor());
                
                int lastTotal = txtTotals.getText().trim().isEmpty() ? 0 : Integer.parseInt(txtTotals.getText().replace(",", ""));
                int newTotal = lastTotal + inventory.getPrice1().multiply(new BigDecimal(prodQty)).intValue(); //ojo
                //Cargar tabla y limpiar los campos
                /*Limpiar elementos de la pantalla*/
            //UtilInv.clearTextFields(this.getContentPane());
                txtProduct.setText("");
                txtProductDesc.setText("");
                txtInStock.setText("");
                ftxtPrice.setValue(null);
                ftxtQuantity.setValue(null);
                txtNote.setText("");
                txtTotals.setText("0");
                //seteando textfield necesarios
                txtTotals.setText(UtilInv.formatNumber(newTotal));
                //txtLastTrans.setText(lastTrans());
                txtProduct.requestFocus();
                loadTable(mainController.getSalesProductTableModel());
//                UtilInv.clearTextFields(this.getContentPane());
                //Restando la cantidad agregada de la info de la base de datos
//                listInvFromDB.get(listInvFromDB.indexOf(inventoryController.findInventory(product.getIdProduct()))).setStock(inStock-prodQty);
                listInvFromDB.get(listInvFromDB.indexOf(inventoryController.findInventory(inventory.getIdInventory()))).setStock(inStock-prodQty);
//                listInvFromDB.forEach(inv ->{
//                    if (Objects.equals(inv.getIdInventory(), inventory.getIdInventory())) {
//                        inv.setStock(inStock-prodQty);
//                    }
//                });
                
            }else if(prodQty <= 0){
                JOptionPane.showMessageDialog(this, "Debe digitar una cantidad mayor a cero...", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Debe digitar una cantidad menor al stock...", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        }
        //arreglar total y limpiar elementos
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        UtilInv.clearTextFields(this.getContentPane());
        loadTable(null);
        txtLastTrans.setText(lastTrans());
        listInvFromDB = inventoryController.findInventoryEntities();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        listInvFromDB = inventoryController.findInventoryEntities();
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAddKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            btnAddActionPerformed(null);
        }
    }//GEN-LAST:event_btnAddKeyPressed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
//        Product p = productController.findProduct(idProductRowClicked);
        if (idProductRowClicked >= 0) {
            mainController.getListInv().remove(idProductRowClicked);
    //        System.out.println(p+" remove: "+remove);
            loadTable(mainController.getSalesProductTableModel());
//                txtLastTrans.setText(String.valueOf(lastNoTrans--));    
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un registro para poder continuar...", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
//        Date date = new Date(datePicker.getText());
//        DateFormat defaultDf = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");//DateFormat.getDateTimeInstance();
//        System.out.println(date);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnOkProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkProductActionPerformed
        jDialogProduct.setVisible(false);
        ftxtQuantity.requestFocus();
    }//GEN-LAST:event_btnOkProductActionPerformed

    private void jTableDialogProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDialogProductMouseClicked
        idProductRowClicked = Integer.parseInt(jTableDialogProduct.getModel().getValueAt(jTableDialogProduct.getSelectedRow(), 0).toString());
        //System.out.println("Row seletecd: "+idProductRowClicked);
        
        if (idProductRowClicked != -1) {
            //for product
            product = productController.findProduct(idProductRowClicked);
            txtProduct.setText(product.getProductCode());
            txtProductDesc.setText(product.getDescription());
            
            listInvFromDB.forEach(i -> {
                    if(i.getIdProduct().equals(product.getIdProduct())){
                        inventory = i;
                    }
                });
            txtInStock.setText(inventory.getStock().toString());
            ftxtPrice.setValue(inventory.getPrice1().intValue());
//            //for supplier
//            supplier = supplierController.findSupplier(idSupplierRowClicked);
//            comboSupplier.setSelectedItem(supplier.getIdSupplier()+"-"+supplier.getName());
//            
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un registro para poder continuar...", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTableDialogProductMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        idProductRowClicked = jTable1.getSelectedRow();//Integer.parseInt(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1).toString());
        System.out.println(idProductRowClicked);
        inventory = inventoryController.findInventory(Integer.parseInt(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0).toString()));
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        System.out.println("Inicializando objetos on windows open");
        initObjects();
        txtClient.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void btnFindClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindClientActionPerformed
        // crear dialog cliente
        loadTableDialogClient(mainController.getClientTableModel());
        jDialogClient.setSize(600, 350);
        jDialogClient.setVisible(true);
    }//GEN-LAST:event_btnFindClientActionPerformed

    private void txtNoteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoteKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnAdd.requestFocus();
        }
    }//GEN-LAST:event_txtNoteKeyPressed

    private void txtClientKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClientKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Ejecutar proceso que busca producto
            Query query = EntityManagerUtil.getEntityManager().createNamedQuery("Client.findByDocument");
            query.setParameter("document", txtClient.getText().trim());
            List<Client> listClient = query.getResultList();
            if (listClient.isEmpty()) {
                System.out.println("Not found, char: "+evt.getKeyChar());
                JOptionPane.showMessageDialog(this, "Cliente no existe en el sistema");
            }else{
                client = listClient.get(0);
                idClientClicked = client.getIdClient();
//                listClient.forEach(c -> {
//                    client = clientController.findClient(c.getIdClient());
//                    System.out.println(c.toString());
//                });

                txtClientName.setText(client.getName());
                txtProduct.requestFocus();

                //                //for supplier
                //                idSupplierRowClicked = product.getIdSupplier();
                //                supplier = supplierController.findSupplier(idSupplierRowClicked);
                //                comboSupplier.setSelectedItem(supplier.getIdSupplier()+"-"+supplier.getName());
            }
        }
        
    }//GEN-LAST:event_txtClientKeyPressed

    private void btnFindProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindProductActionPerformed
        loadTableDialogProduct(mainController.getProductInvTableModel(MainAppController.inventoryController.findInventoryEntities()));
        jDialogProduct.setSize(600, 350);
        jDialogProduct.setVisible(true);
    }//GEN-LAST:event_btnFindProductActionPerformed

//    public Inventory getInvFromProduct (int productId){
//        Inventory inventor = new Inventory();
//        mainController.getListInv().forEach(inv -> {
//            if (inv.getIdProduct() == productId) {
//                inventor = inv;
//            }
//        });
//        return null;
//    }
    private void txtProductKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //Ejecutar proceso que busca producto
            Query query = EntityManagerUtil.getEntityManager().createNamedQuery("Product.findByProductCode");
            query.setParameter("productCode", txtProduct.getText().trim());
            List<Product> listProd = query.getResultList();
            if (listProd.isEmpty()) {
                System.out.println("Not found, char: "+evt.getKeyChar());
                JOptionPane.showMessageDialog(this, "Producto no existe en el sistema");
            }else{
                //Inicializando el objeto product por primera vez
                product = listProd.get(0);
                //Buscando inventario del producto, para mostrar su cantidad disponible inStock
                Query query2 = EntityManagerUtil.getEntityManager().createNamedQuery("Inventory.findByIdProduct");
                query2.setParameter("idProduct", product.getIdProduct());
                List<Inventory> listInventory = query2.getResultList();
                inventory = listInventory.get(0);
                int stock = listInvFromDB.get(listInvFromDB.indexOf(inventory)).getStock();
                inventory.setStock(stock);
                
                txtInStock.setText(inventory.getStock().toString());
                txtProductDesc.setText(product.getDescription());

                ftxtPrice.setText(inventory.getPrice1().toString());
                ftxtQuantity.requestFocus();

                //                //for supplier
                //                idSupplierRowClicked = product.getIdSupplier();
                //                supplier = supplierController.findSupplier(idSupplierRowClicked);
                //                comboSupplier.setSelectedItem(supplier.getIdSupplier()+"-"+supplier.getName());
            }
        }
    }//GEN-LAST:event_txtProductKeyPressed

    private void ftxtQuantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtQuantityFocusGained
        ftxtQuantity.setValue(null);
    }//GEN-LAST:event_ftxtQuantityFocusGained

    private void ftxtQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtQuantityKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtNote.requestFocus();
        }
    }//GEN-LAST:event_ftxtQuantityKeyPressed

    private void ftxtPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtPriceKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ftxtQuantity.requestFocus();
        }
    }//GEN-LAST:event_ftxtPriceKeyPressed

    private void jTableDialogClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDialogClientMouseClicked
        idClientClicked = Integer.parseInt(jTableDialogClient.getModel().getValueAt(jTableDialogClient.getSelectedRow(), 0).toString());
        //System.out.println("Row seletecd: "+idProductRowClicked);
        
        if (idClientClicked != -1) {
            //for product
            client = clientController.findClient(idClientClicked);
            txtClient.setText(client.getDocument());
            txtClientName.setText(client.getName());
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un registro para poder continuar...", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTableDialogClientMouseClicked

    private void btnOkClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkClientActionPerformed
        jDialogClient.setVisible(false);
        txtProduct.requestFocus();
    }//GEN-LAST:event_btnOkClientActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        if (idProductRowClicked >= 0 && evt.getKeyChar() == KeyEvent.VK_DELETE) {
            btnDeleteActionPerformed(null);
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void loadTable(DefaultTableModel model){
        jTable1.setModel(model);
        jTable1.removeColumn(jTable1.getColumnModel().getColumn(0));//to hide the first column ID
        jTable1.removeColumn(jTable1.getColumnModel().getColumn(0));//to hide the first column ID
        jTable1.removeColumn(jTable1.getColumnModel().getColumn(0));//to hide the first column ID
    }
    
    private void loadTableDialogProduct(DefaultTableModel model){
        jTableDialogProduct.setModel(model);
        jTableDialogProduct.removeColumn(jTableDialogProduct.getColumnModel().getColumn(0));//to hide the first column ID
        jTableDialogProduct.removeColumn(jTableDialogProduct.getColumnModel().getColumn(0));//to hide the first column ID
        jTableDialogProduct.removeColumn(jTableDialogProduct.getColumnModel().getColumn(5));
    } 
    
    private void loadTableDialogClient(DefaultTableModel model){
        jTableDialogClient.setModel(model);
        jTableDialogClient.removeColumn(jTableDialogClient.getColumnModel().getColumn(0));//to hide the first column ID
    } 
    
//    private DefaultTableModel getProductDataModel(ProductJpaController productController){
//        String columns[] = {"ID_prod","ID Suplidor" ,"Codigo", "Descripcion", "Categoria", "Precio", "Costo", "Min Stock", "Ideal Stock"};
//        DefaultTableModel tableModel = new DefaultTableModel(columns, 0);
//             
//        productController.findProductEntities().forEach(prod -> {
//            tableModel.addRow(new Object[]{ prod.getIdProduct(),prod.getIdSupplier(), prod.getProductCode(), prod.getDescripcion(), prod.getCategory(), prod.getPrice1() ,prod.getCost(), prod.getMinStock(), prod.getMaxStock()});
//        }); 
//        
//        return tableModel;
//    }
//            
//    private DefaultTableModel getTableDataModel(List<Inventory> list){
//        String columns[] = {"ID","Idprod", "ID_Supplidor", "Codigo", "Descripcion", "Cantidad", "Precio", "Total"};
//        DefaultTableModel tableModel = new DefaultTableModel(columns, 0);
//        
//        try {
//            if(list == null ){
//            //tableModel.addRow(new Object[]{ }); 
//            }else{
//                list.forEach(inv -> {
//                    product = productController.findProduct(inv.getIdProduct());
//                    BigDecimal total =  product.getPrice1().multiply(new BigDecimal(inv.getQuantity()));
//                    tableModel.addRow(new Object[]{inv.getIdInventory(), inv.getIdProduct(), inv.getIdProveedor(), product.getProductCode(), product.getDescripcion(), inv.getQuantity(), product.getPrice1(), total});
//                }); 
//            }
//        } catch (Exception e) {
//            System.out.println(e.getMessage());
//            e.printStackTrace();
//        }
//        
//        return tableModel;
//    }
    
    public String lastTrans(){        
        //numero o ID de la ultima transaccion en esta tabla.
        invTrans = invTransController.findInventoryTransEntities().get(invTransController.getInventoryTransCount()-1);
        lastNoTrans = invTrans.getIdInvTrans();

        //String anio = String.valueOf(invTrans.getCreatedDate().getYear()+1900);
        //System.out.println(anio+"F"+(lastNoTrans+1));
        System.out.println(String.format("%06d", lastNoTrans));

        return String.format("%06d", (lastNoTrans+1));
////        return anio+"F"+(lastNoTrans+1);
//        Calendar cal = new GregorianCalendar();
//        cal.set(Calendar.DAY_OF_YEAR, 1);
////        cal.set(Calendar.YEAR, invTrans.getCreatedDate().getYear()+1900);
////        cal.set(Calendar.DAY_OF_YEAR, 1);
////        cal.set(Calendar.HOUR_OF_DAY, 00);
//        Date start = cal.getTime();
//        
//        //set date to last day of 2014
//        cal.set(Calendar.DAY_OF_YEAR, cal.getActualMaximum(Calendar.DAY_OF_YEAR));
////        cal.set(Calendar.YEAR, invTrans.getCreatedDate().getYear()+1900);
////        cal.set(Calendar.MONTH, Calendar.DECEMBER); // 11 = december
////        cal.set(Calendar.DAY_OF_MONTH, 31); // new years eve
//////        cal.set(Calendar.HOUR_OF_DAY, 24);
//        Date end = cal.getTime();
    }
    
//    private void fillCombo(String combo){
//        if(combo.equals("product")){
//            comboProduct.addItem("");
//            productController.findProductEntities().forEach(prod -> {
//                comboProduct.addItem(prod.getIdProduct()+"-"+prod.getDescripcion());
//            });
//        }else if(combo.equals("client")){
//            comboClient.addItem("");
//            clientController.findClientEntities().forEach(sup -> {
//                comboClient.addItem(sup.getIdClient()+"-"+sup.getName());
//            });
//        } 
//    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductSalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductSalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductSalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductSalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductSalesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFindClient;
    private javax.swing.JButton btnFindProduct;
    private javax.swing.JButton btnOkClient;
    private javax.swing.JButton btnOkProduct;
    private javax.swing.JButton btnSave;
    private com.github.lgooddatepicker.components.DatePicker datePicker;
    private javax.swing.JFormattedTextField ftxtPrice;
    private javax.swing.JFormattedTextField ftxtQuantity;
    private javax.swing.JDialog jDialogClient;
    private javax.swing.JDialog jDialogProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableDialogClient;
    private javax.swing.JTable jTableDialogProduct;
    private javax.swing.JComboBox<String> jcPriceToChoose;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JTextField txtClient;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtInStock;
    private javax.swing.JTextField txtLastTrans;
    private javax.swing.JTextField txtNote;
    private javax.swing.JTextField txtProduct;
    private javax.swing.JTextField txtProductDesc;
    private javax.swing.JTextField txtTotals;
    // End of variables declaration//GEN-END:variables
}
